"""Add APIRequest model

Revision ID: 4709db104861
Revises: 8c8a8ffbf47e
Create Date: 2026-07-26 14:15:25.870759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4709db104861'
down_revision: Union[str, None] = '8c8a8ffbf47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('query_params', sa.String(length=4096), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=False),
    sa.Column('request_body', sa.String(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_headers', sa.JSON(), nullable=False),
    sa.Column('response_body', sa.String(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_requests_id'), 'api_requests', ['id'], unique=False)
    op.create_index(op.f('ix_api_requests_project_id'), 'api_requests', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_requests_project_id'), table_name='api_requests')
    op.drop_index(op.f('ix_api_requests_id'), table_name='api_requests')
    op.drop_table('api_requests')
    # ### end Alembic commands ###

