"""Add Replay model

Revision ID: e52a7e2a79db
Revises: 0055f18f9ac8
Create Date: 2026-07-26 15:03:01.576951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52a7e2a79db'
down_revision: Union[str, None] = '0055f18f9ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_log_id', sa.UUID(), nullable=False),
    sa.Column('replay_status_code', sa.Integer(), nullable=True),
    sa.Column('replay_response_headers', sa.JSON(), nullable=True),
    sa.Column('replay_response_body', sa.JSON(), nullable=True),
    sa.Column('replay_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('replay_success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=4096), nullable=True),
    sa.Column('replayed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_log_id'], ['api_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replays_api_log_id'), 'replays', ['api_log_id'], unique=False)
    op.create_index(op.f('ix_replays_id'), 'replays', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replays_id'), table_name='replays')
    op.drop_index(op.f('ix_replays_api_log_id'), table_name='replays')
    op.drop_table('replays')
    # ### end Alembic commands ###

