"""create code_files table

Revision ID: d995a76761b6
Revises: 6008b9a0e835
Create Date: 2026-07-28 19:31:56.587859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd995a76761b6'
down_revision: Union[str, None] = '6008b9a0e835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('relative_path', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_files_id'), 'code_files', ['id'], unique=False)
    op.create_index(op.f('ix_code_files_repository_id'), 'code_files', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_files_repository_id'), table_name='code_files')
    op.drop_index(op.f('ix_code_files_id'), table_name='code_files')
    op.drop_table('code_files')
    # ### end Alembic commands ###
