"""create code_chunks table

Revision ID: e8dc1938446b
Revises: d995a76761b6
Create Date: 2026-07-28 19:44:03.786885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8dc1938446b'
down_revision: Union[str, None] = 'd995a76761b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code_file_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code_file_id'], ['code_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_chunks_code_file_id'), 'code_chunks', ['code_file_id'], unique=False)
    op.create_index(op.f('ix_code_chunks_id'), 'code_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_chunks_id'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_code_file_id'), table_name='code_chunks')
    op.drop_table('code_chunks')
    # ### end Alembic commands ###
