"""
CodeCompass Chat Schema Validations
"""
from typing import List
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """
    Validation schema for chat requests.
    """
    query: str = Field(..., description="The query or question about the repository.")
    top_k: int = Field(5, ge=1, le=50, description="The maximum number of retrieved chunks to base the response on.")


class Citation(BaseModel):
    """
    Validation schema representing a citation source.
    """
    file_path: str = Field(..., description="Relative path of the cited file.")
    start_line: int = Field(..., description="Start line of the cited snippet.")
    end_line: int = Field(..., description="End line of the cited snippet.")


class ChatResponse(BaseModel):
    """
    Response schema for AI RAG chat responses.
    """
    answer: str = Field(..., description="The answer generated by the LLM.")
    retrieved_files: List[str] = Field(..., description="List of unique file paths retrieved.")
    retrieved_code_snippets: List[str] = Field(..., description="List of raw code chunk contents retrieved.")
    citations: List[Citation] = Field(..., description="Citations linking snippets to their sources.")
